### ISSUE TITLE
Benchmarks also measure data creation

### ISSUE THREAD

**Issue by CdRGit** [gardc/language-benchmarks#1]
Your benchmarks are also including the data creation step, giving rust (and possibly go, tho I have less knowledge about go's RNG) a massive disadvantage as rand::thread_rng is a cryptographically secure PRNG that samples fresh entropy every 64KiB of data generated (that is approximately 490 times in this test)

**Comment by gardc** [comment]
Thank you for pointing this out. Spending more than a short hour on this benchmark, I believe it has been fixed in [#13d81fd](https://github.com/gardc/language-benchmarks/commit/13d81fdef23860aae9afdad720be5b6bdbb8468c) by moving the generation step out of the equation.

This also includes adding AOT compilation for C# which originally was a disadvantage for the C# results.
